### ISSUE TITLE
Publish succeeds on non-local cluster but application becomes unhealthy immediately.

### ISSUE THREAD

**Issue by zoalasaurusrawr** [c3-ls/ServiceFabric-Http#15]
I am  
**Error event: SourceId='System.Hosting', Property='CodePackageActivation:C:EntryPoint'.**
There was an error during CodePackage activation.The service host terminated with exit code:1

**Seeing this on both HttpGatewayService and HttpServiceService:**
Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count.

I'm not sure how much of this is truly the app vs. my inexperience with ServiceFabric thus far.

**Comment by zoalasaurusrawr** [comment]
Getting closer: I discovered this error on my local cluster. I assume that's why package activation is failing.

Project does not contain any commands in project.json and cannot be started directly

EDIT: This error was for the HttpServiceGateway.

**Comment by cwe1ss** [comment]
Troubleshooting non-starting services is a bit of a pain in Service Fabric. we usually check the following things:
- C:\SfDevCluster\Data_App\Node.**x**\**ApplicationTypeFolder**\log -> this contains the console output of your service.
- Event Log -> Service Fabric has its own subfolder there
- [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) -> that's a complicated but amazing tool to monitor ETW events and other stuff. Since .net exceptions are logged as ETW events as well it sometimes shows you startup exceptions. Run it, go to "Collect -> Collect". De-Select "Merge". Click "Start Collection". Now kill your service fabric service in task explorer. Moments later, Service Fabric will start it again. After it failed, "Stop collection" in PerfView. Now double-click on "Events" in the left tree - this will open all recorded ETW events. Search for "Microsoft-Windows-DotNETRuntime/Exception/Start" and double click on it. You should see all .NET exceptions that occured, ordered by time. 

Hope this helps!

**Comment by cwe1ss** [comment]
Too be fair, it's not that much about Service Fabric - it's more about dnx based hosting. We constantly ran into the 260 character path limit and got weird exceptions because with dnx, everything is compiled at startup.

That's why we already moved to dotnet cli based hosting. The master branch already targets an RC2 daily build and it also contains a new Hosting-project which I haven't yet had time to document. Unfortunately, if you want to use that, I guess you have to be on the same daily build and so on. Until RC2 is released, all of this is pretty painful. :-(

**Comment by zoalasaurusrawr** [comment]
I can deal with pain!

This is an amazing project, so I'm happy to do whatever I need to do to provide feedback and keep this going.

Once I get a better understanding of the end to end product (Once I have it working), I was planning to contribute a few basic tutorials for calling into the generic gateway for components.

I will dig through logs and keep trying things. I will update this issue with my findings.

**Comment by zoalasaurusrawr** [comment]
Finally got details I didn't receive before.

Unhealthy event: SourceId='System.PLB', Property='ServiceReplicaUnplacedHealth_Secondary_a314cda6-f956-44fd-a314-9775afd05848', HealthState='Warning', ConsiderWarningAsError=false.
The Load Balancer was unable to find a placement for one or more of the Service's Replicas:
fabric:/GatewaySample/HttpServiceService Secondary Partition a314cda6-f956-44fd-a314-9775afd05848 could not be placed, possibly, due to the following constraints and properties:  
Placement Constraint: N/A
Depended Service: N/A

Constraint Elimination Sequence:
NodeBlockList eliminated 3 possible node(s) for placement -- 0/3 node(s) remain.

At this point I feel like I'm not setting the partition correctly. We are using an on-premise cluster with three nodes.

**Comment by cwe1ss** [comment]
Is your cluster already using the GA-version of Service Fabric? The projects here still target the preview version (we haven't yet upgraded). Maybe something changed in the ServiceManifest.xml that doesn't allow them to be started - but that's just a guess...

I will update to the GA version of the SDK soon - unfortunately it has some breaking changes so I have to resolve them first.

**Comment by zoalasaurusrawr** [comment]
We are using the GA version. I will keep a watch out on this repo. I'm very interested in this project :smile: 

I'm going to keep tinkering with it to try and understand SF better. So many new variables to deal with all at once, lol.

**Comment by cwe1ss** [comment]
I guess this is no longer relevant. Re-open it if there's still something to do here.
