### ISSUE TITLE
Where can I help?

### ISSUE THREAD

**Issue by zoalasaurusrawr** [c3-ls/ServiceFabric-Http#17]
My company is very formally asking me to help contribute and get the product fully ported to RC2 along with getting the code working on the GA version of service fabric.

Where can I help, give me anything and I'll be happy to jump in!

**Comment by cwe1ss** [comment]
Hi, I upgraded the code yesterday [in a new branch](https://github.com/c3-ls/ServiceFabric-HttpServiceGateway/tree/sf2), however I have not yet tested it. (I couldn't publish due to dnu publish issues). 

So if you have time to test that branch, that would be great!

the main change in the Service Fabric SDK has been that the CommunicationClientFactory no longer does the exception handling. Instead, they now fully moved to custom `IExceptionHandler` classes.

I changed the following things so far (I will update the docs as soon as everything is ready):
- HttpCommunicationOptions.DoNotRetryExceptionTypes was removed. A custom `IExceptionHandler` should be used instead. (if you use the HttpCommunication library outside of the gateway, you can also pass a list of exception types to the `ServicePartitionClient` constructor)
- HttpCommunicationOptions.ExceptionHandlers removed: the code now supports dependency injection, so you can add your own exception handlers through `services.Add<IExceptionHandler, CustomExceptionHandler>()`
- HttpServiceGatewayOptions.Int64PartitionKeyResolver and Named\* have been merged to `ServicePartitionKeyResolver`
- `HttpServiceGatewayOptions.ListenerName` is new! As far as I understand it, this allows to select the endpoint name in case there are more (which should resolve #13 )
- better exception text if endpoint url is not an http url (also for #13 )
- I changed all ASP.NET Core dependencies to "1.0.0-rc2-*" so it now points to the most current RC2 daily build on the aspnetvnext feed.
- I also changed a few things to make sure it compiles with "dotnet cli", however I have not yet tested much here

**Comment by zoalasaurusrawr** [comment]
Wonderful, I am about to leave for the weekend here. I will use this thread for updates (unless Github has a better way).

I plan on going full on into this Monday morning!

Thanks again!!!

**Comment by cwe1ss** [comment]
I want to make sure you invest your time at the right project, so I was wondering if you know about the [other Service Fabric gateway](https://github.com/weidazhao/Hosting) from a Microsoft employee? It looks like this might end up in the SDK someday. We implemented this at the same time and our implementations are very similar. I even tried to get closer to their implementation with the current changes.

So if you want to go with something a little bit more official, that project might be interesting for you as well!

However, I still consider our project to be a little bit better! :-) See https://github.com/weidazhao/Hosting/issues/4 for some differences. I think the main advantages of our library are the separate HttpCommunication library (if you want to have direct HTTP communication between services) and better error handling. If you only need the error handling but you want to use the other gateway, you can now also just copy the IExceptionHandler from here and use it with their gateway.

Ideally, our projects should get merged, but I haven't yet had the time to come up with a good PR.

The `C3.ServiceFabric.AspNetCore.Hosting` project has a different approach than the other library and is not related to the gateway functionality itself. With this library, you can work locally completely without the requirement to deploy to Service Fabric. The library makes sure it only attaches itself to Service Fabric, when the command line arg "--fabric true" is added. This is a HUGE time saver during development, but of course, this only works for stateless services!

**Comment by zoalasaurusrawr** [comment]
I'm glad to see that this area is blossoming so much. I'm happy sticking to this project.

We are very comfortable with open source tech from smaller channels! We looked over multiple projects and we really love this one.

EDIT: I will start testing today, I'll update you on how that goes!

**Comment by cwe1ss** [comment]
I'll close this. create a new issue if you want to work on a specific feature.
