### ISSUE TITLE
What are the benefits of using this communication implementation vs the SF default/built-in?

### ISSUE THREAD

**Issue by HakanL** [c3-ls/ServiceFabric-Http#27]

**Comment by cwe1ss** [comment]
I guess it's a personal preference. We prefer HTTP because it's an open protocol that makes it easier for us to use open standards like OAuth2 for authorization and swagger/swagger-ui for easy testing. By using ASP.NET Core we also get the additional advantages of using middleware components to easier integrate stuff like logging, monitoring, ...

**Comment by HakanL** [comment]
Good, thanks for the info.
