### ISSUE TITLE
Dynamic Gateway

### ISSUE THREAD

**Issue by noocyte** [c3-ls/ServiceFabric-Http#34]
We want to build a dynamic HTTP gateway; where services can register their routes dynamically. The implication of course is then that the gateway itself does not know about any of the routes. Our goal is to avoid updates to the gateway itself. 

I have taken the liberty to copy the gateway middleware and request/response message extension code into our own. Some minor adjustments to that code has also been applied and I now have a working POC going. The POC is available here: https://github.com/noocyte/HttpGatewayPOC

Obviously I'd be happy to contribute anything useful back of this code.

Our solution is also a multi-tenant solution so I'm using SaasKit to provide that.

**Comment by cwe1ss** [comment]
Hi, thanks for sharing this!

Supporting a scenario that allows the gateway to dynamically route requests without having to restart it definitely is something that would be beneficial!

Integrating an external dependency like SaasKit on the other hand is not something I'd like to see integrated into the core. If that's useful for more people we should think about whether we can make this a pluggable solution which people could opt-in via a separate library.

However, I stopped working on the gateway for now because we still have to figure out whether the [now built-in gateway](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reverseproxy/) from Service Fabric will make this project obsolete for us. I'll create a separate issue to ask people who follow this project whether they still want to use this project.

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
