### ISSUE TITLE
Comparison with the new official Service Fabric Gateway service

### ISSUE THREAD

**Issue by cwe1ss** [c3-ls/ServiceFabric-Http#37]
Service Fabric recently added an integrated gateway service. You can read more about it [in their documentation](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reverseproxy/).

We haven't done any tests with the official gateway yet so I can't yet say whether we will move. If we move, I'm afraid we wouldn't be able to enhance this project (doesn't make much sense if we are not using it ourselves).

Have people who were using our gateway already moved to this official gateway or do you still see value/use-cases for our solution?

I'd appreciate your feedback!

**Comment by noocyte** [comment]
The reverse proxy is 'useless' for us; we want to expose 'pretty urls' and handle authentication in one place. Then forward the request to our internal services. So we're building our own gateway, partially based on this code.

**Comment by cwe1ss** [comment]
Thanks for your feedback @noocyte! 

Good point! AFAIU, you almost never would want to expose the integrated offical gateway service directly to the internet because it exposes _every_ service. Usually you would only want to expose your frontend services (e.g. the web application itself and not the backend services).

However, no matter if you use our gateway or the official one, as long as it uses subdirectories for your different services, you'd need another proxy/gateway in front of it to map it to "pretty domains" (e.g. www.my-app.com to mycluster.domain.com/my-app )

Azure Application Gateway would be one solution for this, however it doesn't support adding subdirectories to backend pools. There's a [feedback request](https://feedback.azure.com/forums/217313-networking/suggestions/12239826-support-url-rewriting-with-application-gateway) for this marked as "Planned" but as we all now, this doesn't mean much... Could be months, could be years :smile:

So if I'm right, there's no PaaS solution for this right now and you would have to host e.g. your own NGINX instances.

Since our gateway can also be used on the root path (but just for one service of course), you could use different instances with different ports for each public service. This way you could either expose it directly through a public load balancer or you could use Azure Application Gateway in front of it.

If we will stay with our gateway, we might enhance it to do port-based forwarding in one instance. Meaning, on startup we would just listen on multiple endpoints and decide based on the port which service the traffic will be forwarded to.

**Comment by cwe1ss** [comment]
@noocyte Could you also share a list of things you will do different in your gateway? Just curious to see if we can "join forces" and keep this in one project, should we decide to continue using it.

**Comment by noocyte** [comment]
We want to expose parts of our internal services to the outside. As an example we have a RuntimeSettings service where we can store 'stuff', useful for stateless services that need a little bit of state only. It would then make sense to expose the get/put part of that (there's more to it) though our public API so that we could inspect the values etc. One way of doing that is to add a route to the gateway and redeploy it (gateway). However this approach does not scale and becomes very tedious when we add 10s of services... So we want to build a Dynamic Gateway Router (tm) where internal services register their 'route' and the gateway forwards matching requests to the internal service. We use a stateful service to hold the routes and the gateway requests routes on startup and as the routes change the stateful router service pings the gateway with updates.

Authentication needs to be handled in the gateway, we build an 'IdentityModel' object in ours that is passed a long with the request (header) so the only place where we check for authentication is in teh gateway/router. 

For the gateway to be able to reach our stateful services it needs to understand our partition strategy, which is pretty simple to be honest. But it does add quite a bit of specific logic to it. 

We'd be happy to share our code, but it is not 'done' yet. In fact we have a major challenge with SignalR missing (still) for ASP.Net Core... And when it's available we'll be running a Hub on our gateway as well, though I guess we could forward SignalR requests as well, I've seen example code of doing that (Web sockets). We'll see what we do when we get there...
