### ISSUE TITLE
[Clarification] Exposing gateway to the external client

### ISSUE THREAD

**Issue by SergiiKliebanov** [c3-ls/ServiceFabric-Http#39]
Hi guys,
Currently I'm looking for a gateway I can use on top of my microservices. There is a gap I couldn't fill while reading Reverse Proxy documentation and issues related to other gateways - what is the proper way to expose gateway's address to the external client? In my case it will be Angular application.

It is clear we need to resolve addresses for internal calls inside the cluster, but how should external client get gateway's address since gateway is the same Service Fabric service which can be hosted on any of nodes according to current configuration and health status of cluster.
I can define a fixed port for gateway's `Endpoint ` in the `ServiceManifest`, but I still don't know the machine gateway will be running on.

**Comment by cwe1ss** [comment]
Whenever you want to expose a service to the outside world (no matter if it's a gateway or any other service) you need a public IP address. This also means that you need a component that forwards traffic from this public IP address to your corresponding service - in other words, you need a load balancer!

On Azure, you can either use the regular "Azure Load Balancer" for TCP-based load balancing or "Azure Application Gateway" for HTTP-based load balancing (so you also get SSL offloading, Web Application Firewall, ...).
If you look at the resources in your Service Fabric resource group, you'll see that there already is one load balancer - this one is used by Service Fabric itself for the public "Service Fabric Explorer", the management endpoints and (if you've enabled it) the built-in reverse proxy. 

If you want to expose one of your own services, it's best to use a separate load balancer with a separate public IP. 

The load balancer needs two things: a backend pool (= a service fabric node type) and a backend port it should forward the traffic to. 

This means you need to assign a fixed port to your service (as described in your last paragraph)! 

Since the load balancer will automatically forward traffic to ALL nodes in your node type, you have multiple options to define the number of instances for your service.
* You can specify `InstanceCount=-1` for your service. This will ensure that there's a service on each of your nodes. This might be a good solution if you have a small cluster.
* You can rely on the load balancer probes. E.g. if you have 10 nodes in your node type and you want your service just on 3 nodes, the load balancer would automatically figure out that there's no listening service on 7 nodes so it will stop sending traffic to them. However, this results in failed requests until the load balancer has figured this out, so I wouldn't recommend this for production.
* You can use multiple node types. If you're building a bigger cluster, you can create multiple node types where one is the "frontend" node type that is configured to receive traffic from the load balancer. You'll then use `InstanceCount=-1` and a `(nodeType==frontend)` "placement constraint" on your service to ensure that it will run on each frontend server (and nowhere else). This way, the load balancer can still send traffic to all nodes from the node type.

Hope this helps?!

**Comment by SergiiKliebanov** [comment]
@cwe1ss, thanks for the detailed answer! Yes, it's clear now 👍

**Comment by cwe1ss** [comment]
You're welcome!
