### ISSUE TITLE
How to setup the adjusted URLs in services

### ISSUE THREAD

**Issue by tbernt** [c3-ls/ServiceFabric-Http#43]
On the Wiki is a document found about the adjustment of the Root URL of forwarded requests to a service (https://github.com/c3-ls/ServiceFabric-Http/wiki/Adjusting-absolute-URLs-in-services). How do use this mentioned Method  “private static string GetRootUrl(HttpRequestMessage request)” or where do I have to set the RootUrl on a stateless service (asp.net core)?

**Comment by cwe1ss** [comment]
The wiki page only contains an example of how to extract the gateway URL prefix from the request. You can use this code (or a simpler version if you don't want to use the `Forwarded` AND `X-Forwarded-*` headers) wherever you want. 

It seems like with Swashbuckle, the usage has changed and you have to use `PreSerializeFilters` now instead of a separate `RootUrl()` method - see [this comment](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/427#issuecomment-329641536) for an example.

You could also write a simple ASP.NET Core middleware that runs early in your pipeline and sets the PathBase with this method.

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
